import type { RestorePoint } from "@/lib/types/page-customization"
import { defaultPageLayouts } from "./page-layouts"

// Restore points - admin can restore to these
export const restorePoints: RestorePoint[] = [
  {
    id: "restore-1",
    pagePath: "/",
    layout: defaultPageLayouts["/"],
    createdAt: "2024-01-01T00:00:00Z",
    createdBy: 0, // System
    description: "Initial default layout",
    isAutoGenerated: true,
  },
  {
    id: "restore-2",
    pagePath: "/transactions",
    layout: defaultPageLayouts["/transactions"],
    createdAt: "2024-01-01T00:00:00Z",
    createdBy: 0,
    description: "Initial default layout",
    isAutoGenerated: true,
  },
]

