import mongoose, { Schema, Document } from "mongoose"
import type { IPageLayout } from "./PageLayout"

export interface IRestorePoint extends Document {
  _id: mongoose.Types.ObjectId
  id: string
  pagePath: string
  layout: IPageLayout
  createdAt: Date
  createdBy: number
  description: string
  isAutoGenerated: boolean
}

const RestorePointSchema = new Schema<IRestorePoint>(
  {
    id: { type: String, required: true, unique: true },
    pagePath: { type: String, required: true },
    layout: { type: Schema.Types.Mixed, required: true }, // Store full layout object
    createdBy: { type: Number, required: true },
    description: { type: String, required: true },
    isAutoGenerated: { type: Boolean, default: false },
  },
  {
    timestamps: { createdAt: true, updatedAt: false },
    collection: "restore_points",
  }
)

// Create indexes
RestorePointSchema.index({ id: 1 })
RestorePointSchema.index({ pagePath: 1 })
RestorePointSchema.index({ createdAt: -1 })

export function createRestorePointModel(connection: mongoose.Connection) {
  return connection.models.RestorePoint || connection.model<IRestorePoint>("RestorePoint", RestorePointSchema)
}

