export interface PageElement {
  id: string
  type: "card" | "chart" | "list" | "metric" | "custom"
  component: string // Component name/identifier
  props?: Record<string, any> // Component props
  position: number // Order/position on page
  isVisible: boolean
  config?: Record<string, any> // Additional configuration
}

export interface PageLayout {
  id: string
  pagePath: string // e.g., "/", "/transactions", etc.
  elements: PageElement[]
  version: number
  createdAt: string
  updatedAt: string
  createdBy: number // User ID
  updatedBy: number // User ID
}

export interface RestorePoint {
  id: string
  pagePath: string
  layout: PageLayout
  createdAt: string
  createdBy: number // User ID who created the restore point
  description?: string
  isAutoGenerated: boolean // true for automatic saves, false for manual
}

export interface PageCustomizationInput {
  pagePath: string
  elements: PageElement[]
}

