import type { PageLayout, PageElement, PageCustomizationInput, RestorePoint } from "@/lib/types/page-customization"
import { currentPageLayouts, defaultPageLayouts } from "@/lib/data/page-layouts"
import { restorePoints } from "@/lib/data/restore-points"

/**
 * Get current layout for a page
 */
export function getPageLayout(pagePath: string): PageLayout | null {
  return currentPageLayouts[pagePath] || null
}

/**
 * Get default layout for a page
 */
export function getDefaultPageLayout(pagePath: string): PageLayout | null {
  return defaultPageLayouts[pagePath] || null
}

/**
 * Update page layout (dev/admin can do this)
 */
export function updatePageLayout(pagePath: string, input: PageCustomizationInput, userId: number): PageLayout {
  const now = new Date().toISOString()
  const existingLayout = currentPageLayouts[pagePath]
  
  const newLayout: PageLayout = {
    id: existingLayout?.id || `${pagePath}-layout`,
    pagePath,
    elements: input.elements,
    version: (existingLayout?.version || 0) + 1,
    createdAt: existingLayout?.createdAt || now,
    updatedAt: now,
    createdBy: existingLayout?.createdBy || userId,
    updatedBy: userId,
  }
  
  currentPageLayouts[pagePath] = newLayout
  
  // Auto-create restore point for admin review
  createRestorePoint(pagePath, newLayout, userId, true)
  
  return newLayout
}

/**
 * Add element to page
 */
export function addPageElement(pagePath: string, element: PageElement, userId: number): PageLayout | null {
  const layout = getPageLayout(pagePath)
  if (!layout) return null
  
  const updatedElements = [...layout.elements, element].sort((a, b) => a.position - b.position)
  
  return updatePageLayout(
    pagePath,
    { pagePath, elements: updatedElements },
    userId
  )
}

/**
 * Remove element from page
 */
export function removePageElement(pagePath: string, elementId: string, userId: number): PageLayout | null {
  const layout = getPageLayout(pagePath)
  if (!layout) return null
  
  const updatedElements = layout.elements.filter((el) => el.id !== elementId)
  
  return updatePageLayout(
    pagePath,
    { pagePath, elements: updatedElements },
    userId
  )
}

/**
 * Update element visibility
 */
export function toggleElementVisibility(pagePath: string, elementId: string, userId: number): PageLayout | null {
  const layout = getPageLayout(pagePath)
  if (!layout) return null
  
  const updatedElements = layout.elements.map((el) =>
    el.id === elementId ? { ...el, isVisible: !el.isVisible } : el
  )
  
  return updatePageLayout(
    pagePath,
    { pagePath, elements: updatedElements },
    userId
  )
}

/**
 * Reorder elements
 */
export function reorderElements(pagePath: string, elementIds: string[], userId: number): PageLayout | null {
  const layout = getPageLayout(pagePath)
  if (!layout) return null
  
  const elementMap = new Map(layout.elements.map((el) => [el.id, el]))
  const updatedElements = elementIds
    .map((id, index) => {
      const element = elementMap.get(id)
      return element ? { ...element, position: index } : null
    })
    .filter((el): el is PageElement => el !== null)
  
  return updatePageLayout(
    pagePath,
    { pagePath, elements: updatedElements },
    userId
  )
}

/**
 * Create a restore point (admin can do this manually, or auto-created on changes)
 */
export function createRestorePoint(
  pagePath: string,
  layout: PageLayout,
  userId: number,
  isAutoGenerated: boolean = false,
  description?: string
): RestorePoint {
  const restorePoint: RestorePoint = {
    id: `restore-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    pagePath,
    layout: JSON.parse(JSON.stringify(layout)), // Deep copy
    createdAt: new Date().toISOString(),
    createdBy: userId,
    description: description || (isAutoGenerated ? "Auto-generated restore point" : "Manual restore point"),
    isAutoGenerated,
  }
  
  restorePoints.push(restorePoint)
  // Keep only last 50 restore points per page
  const pageRestorePoints = restorePoints.filter((rp) => rp.pagePath === pagePath)
  if (pageRestorePoints.length > 50) {
    const toRemove = pageRestorePoints.slice(0, pageRestorePoints.length - 50)
    toRemove.forEach((rp) => {
      const index = restorePoints.indexOf(rp)
      if (index > -1) restorePoints.splice(index, 1)
    })
  }
  
  return restorePoint
}

/**
 * Get restore points for a page
 */
export function getRestorePoints(pagePath: string): RestorePoint[] {
  return restorePoints
    .filter((rp) => rp.pagePath === pagePath)
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
}

/**
 * Restore page to a restore point (admin only)
 */
export function restorePageLayout(pagePath: string, restorePointId: string, userId: number): PageLayout | null {
  const restorePoint = restorePoints.find((rp) => rp.id === restorePointId && rp.pagePath === pagePath)
  if (!restorePoint) return null
  
  const restoredLayout = JSON.parse(JSON.stringify(restorePoint.layout)) // Deep copy
  restoredLayout.updatedAt = new Date().toISOString()
  restoredLayout.updatedBy = userId
  restoredLayout.version = (currentPageLayouts[pagePath]?.version || 0) + 1
  
  currentPageLayouts[pagePath] = restoredLayout
  
  // Create a new restore point for this restoration
  createRestorePoint(pagePath, restoredLayout, userId, false, `Restored from: ${restorePoint.description}`)
  
  return restoredLayout
}

/**
 * Reset page to default layout (admin only)
 */
export function resetPageToDefault(pagePath: string, userId: number): PageLayout | null {
  const defaultLayout = getDefaultPageLayout(pagePath)
  if (!defaultLayout) return null
  
  const resetLayout: PageLayout = {
    ...defaultLayout,
    version: (currentPageLayouts[pagePath]?.version || 0) + 1,
    updatedAt: new Date().toISOString(),
    updatedBy: userId,
  }
  
  currentPageLayouts[pagePath] = resetLayout
  
  // Create restore point for this reset
  createRestorePoint(pagePath, resetLayout, userId, false, "Reset to default layout")
  
  return resetLayout
}

